const ROUTE_CHANGE = 'ROUTE_CHANGE'
const EDIT_FIELDS = 'EDIT_FIELDS'
const UPDATE_CELL_VALUE = 'UPDATE_CELL_VALUE'
const SOLVE_SUDOKU = 'SOLVE_SUDOKU'
export {
  EDIT_FIELDS,
  UPDATE_CELL_VALUE,
  SOLVE_SUDOKU,
  ROUTE_CHANGE
}
